### PR TITLE
Bug Fix: Installing, activating, deactivating, and deleting a plugin does not wipe/clear the cache; see: websharks/zencache#424

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/zencache#424

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc Can we add a filter here to disable this behavior should a site owner want to do so?

**Comment by raamdev** [comment]
@jaswsinc Ping. ↑

**Comment by jaswsinc** [comment]
@raamdev I see no problem with that.

## @renzms Next Actions

- Before [this line](https://github.com/websharks/zencache-pro/blob/6eeeb6f2d50240351ba5496a08929ef315d9f16e/src/includes/closures/Plugin/WcpPluginUtils.php#L18) add the following:

  ```php
  if (!$self->applyWpFilters(GLOBAL_NS.'_auto_clear_on_plugin_activation_deactivation', true)) {
      return 0; // Nothing to do here.
  }
  ```

**Comment by renzms** [comment]
@jaswsinc /@raamdev

PR submitted!

**Comment by raamdev** [comment]
@renzms Thanks! Tested and merged. :-)

**Comment by jaswsinc** [comment]
:+1:

**Pull request closed without merging**
