### PR TITLE
Add logged-in check for CDN; See: websharks/zencache#486

### PR DESCRIPTION
**Pull request by kristineds**
Add logged-in check for CDN; 

- Update codebase to utilize this new option when determining if Static CDN Filters should be applied.
- This is Step 1 of 2. _Note: Don't merge until Step 2 has been completed_

See: websharks/zencache#486

### CODE REVIEW

**Comment by raamdev** [comment]
@kristineds Can you give me a status update on Step 2, please? I'm trying to figure out if we can get websharks/zencache#486 closed for the RC this Friday so that this work can be included in the next release. :-)

**Comment by kristineds** [comment]
@raamdev I just submitted the recent PR for this. :) Not really sure how to revise the description so there's no conflicting information. https://github.com/websharks/zencache-pro/pull/189#issuecomment-161317772

**Comment by raamdev** [comment]
@kristineds The https://github.com/websharks/zencache-pro/pull/189#issuecomment-161317772 link links to this PR... :-)

**Comment by raamdev** [comment]
@kristineds Merged. Thank you. :smile:

**Pull request closed without merging**
