### PR TITLE
Bug Fix - Pagination Var Translation Breaks Cache Clearing step2

### PR DESCRIPTION
**Pull request by renzms**
see: websharks/zencache#607

### CODE REVIEW

**Comment by jaswsinc** [comment]
@renz Looks great! Awesome work on this man.

I noticed there is [one more instance](https://github.com/websharks/zencache-pro/blob/1036b88de36dc5c4c552d838f5a0380cc90fe04a/src/includes/closures/Shared/CachePathUtils.php#L224) where we need to make the change.

  Change:

  ```php
  $regex_suffix_frag = (string) $regex_suffix_frag;
  ```

  to:

  ```php
  $regex_suffix_frag = $self->cachePathRegexSuffixFrag($regex_suffix_frag);
  ```

**Comment by jaswsinc** [comment]
Looks great! Thank you.

**Comment by raamdev** [comment]
@jaswsinc between https://github.com/websharks/zencache-pro/pull/179 and this PR, does this look ready to merge?

**Comment by jaswsinc** [comment]
Yes. This looks great! Ready to merge in my view.

**Comment by raamdev** [comment]
Merging this into https://github.com/websharks/zencache-pro/pull/179 and closing this PR in favor of https://github.com/websharks/zencache-pro/pull/179 .

**Pull request closed without merging**
