### PR TITLE
Add new option to update to latest beta release; See: websharks/zencache#352

### PR DESCRIPTION
**Pull request by kristineds**
Add new option to update to latest beta release; 

- Add new configurable option to the UI that controls the value of `pro_update_check_stable`
- This is step 2 of 2: Feature Request: Option to Check for Latest Release Candidate (Beta)
- This is a work in progress. It is missing a new icon for the menu header and I would probably need some help with the text description.

UI for Update Beta Release

See: websharks/zencache#352

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting latest commit: https://github.com/websharks/zencache-pro/commit/3c761b987740a5e2c46eaf12f85de14b4523dbe3. Changes include

- Revised text description
- Updated code for the UI option: Should use `pro_update_check_stable` and `stable` which was added on Step 1

**Comment by jaswsinc** [comment]
@kristineds Lookin' great! Here are some additional steps that will be needed for this to work.

- Change `[check][stable]` in [this line](https://github.com/websharks/zencache-pro/commit/3c761b987740a5e2c46eaf12f85de14b4523dbe3#diff-9af81f78ee7fe586d465a5be074679a7R130) to `[check_stable]`

- After [this line](https://github.com/websharks/zencache-pro/blob/151105/src/includes/classes/Actions.php#L662) add the following:

  ```php
  if (!isset($args['check_stable'])) {
      $args['check_stable'] = $this->plugin->options['pro_update_check_stable'];
  }
  ```

- After [this line](https://github.com/websharks/zencache-pro/blob/151105/src/includes/classes/Actions.php#L694) add the following:

  ```php
  'pro_update_check_stable' => $args['check_stable'],
  ```

**Comment by raamdev** [comment]
@kristineds Woohoo! I love that this feature is finally becoming a reality! :-)

Here are a few requested edits:

- [ ] Update the description to the following: "If you would like to participate in our beta program and receive new features and bug fixes before they are released to the public, ZenCache can notify you when a new Release Candidate is available for testing. Release Candidates are almost-ready-for-production and have already been through many internal test runs. Our team runs the latest Release Candidate on all of our production sites, but that doesn't mean you'll want to do the same. :-) Please report any issues with Release Candidates on <a href="http://github.com/websharks/zencache/issues/">GitHub</a>."
- [ ] Change the H3 inside the option panel to "ZenCache™ Beta Testers"
- [ ] Change the panel title to "Beta Testers"
- [ ] Use the "Flask" icon for the panel icon

@jaswsinc Should be able to help you with how to add the Flask Icon; sorry, it's not immediately obvious to me. The icon is included with the Sharkicons library that gets distributed with ZenCache (search [this page](http://websharks.github.io/sharkicons/demo.html) for "flask").

**Comment by raamdev** [comment]
@kristineds If you're currently viewing this page, please note that I made a few edits to my previous comment with a few additional todo items. Just hit refresh on this page to make sure you have the latest version. :-)

**Comment by kristineds** [comment]
@jaswsinc @raamdev PR re-submitted with those changes you pointed out. :+1: 

ZenCache Updated Beta Testers UI Option

**Comment by raamdev** [comment]
@kristineds Beautiful! One last thing: could you please remove the `style="text-decoration:none;"` from both of the links in that panel? Hiding the text decoration makes the links really hard to notice. :-)

**Comment by jaswsinc** [comment]
@kristineds That looks beautiful. I love the flask icon!

**Comment by kristineds** [comment]
@jaswsinc @raamdev 

Removed the `style="text-decoration:none;"` ;)

ZC Beta testers

**Comment by raamdev** [comment]
@kristineds You missed the "beta testers mailing list" link; that shouldn't have the `text-decoration:none` either. :-)

**Comment by kristineds** [comment]
@raamdev Oops. Here you go. https://github.com/websharks/zencache-pro/commit/ecfcc4332de536d59bdfb595b2c8f4799e316acf

ZC beta testers

**Comment by raamdev** [comment]
@kristineds Thank you! :-)

@jaswsinc Between this PR and https://github.com/websharks/zencache-pro/issues/176 (Step 1), is this feature-complete? I've been following along but between the [work you did initially to update the product API](https://github.com/websharks/zencache/issues/352#issuecomment-140740386) and the work you outlined for Kristine, I'm not entirely certain if anything else is missing or if this feature is now ready for testing. :-)

**Comment by jaswsinc** [comment]
@raamdev Yep. Ready for testing now.
@kristineds _Really_ nice work on this!

**Comment by raamdev** [comment]
@jaswsinc @kristineds I've merged the changes from this branch into the Step 1 branch (https://github.com/websharks/zencache-pro/pull/176) and I'm going to close this PR in favor of testing and pushing further updates to that single PR (to lessen confusion). 

Awesome work here @kristineds! :-)

**Comment by kristineds** [comment]
@jaswsinc @raamdev Glad to help! Looking forward for that feature to be part of the next release. :+1:

**Pull request closed without merging**
