### PR TITLE
Prepare generated-Lite version for release

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/zencache.com#74

---

### Work that needs to be done:

- [x] Fix Phing build script so that it properly generates the Lite version (as of 2015-12-23, the images in `src/client-s/images/` are all `0` bytes in the Lite-generated version). 

     **<del>Pending merge of</del> Merged: https://github.com/websharks/phings/issues/24**
- [x] Update Phing build scripts so that Pro-only files are excluded from Lite-generated version.

     **<del>Pending merge of</del> Merged: https://github.com/websharks/phings/issues/26**
- [x] Review Lite-generated files to ensure there is no corruption and that Pro-only sections were stripped out properly and that all features of the Lite-generated version work as expected.
- [x] Update Pro Preview with style improvements (see https://github.com/websharks/zencache.com/issues/58#issuecomment-120087055)
- [x] Add Dashboard messages appropriate to upgrading from the the old codebase to the new codebase; see https://github.com/websharks/zencache.com/issues/68.
- [x] Update build script so that it converts all text domain references in the Lite version into string literals for translate.wordpress.org (e.g., `'zencache'` instead of `SLUG_TD` or `$this->text_domain`).

     <del>**Pending merge of https://github.com/websharks/phings/issues/30**</del>

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc If you could help me with that first item, where the Phing build script seems to be copying the `src/client-s/images/*` with a `0` byte length, that would be great. I dug into the build scripts a bit but nothing jumped out at me. The files seem to copy as expected, but why those images (and apparently _only_ those image files) are ending up with `0` byte length is a mystery to me.

**Comment by raamdev** [comment]
> If you could help me with that first item, where the Phing build script seems to be copying the src/client-s/images/* with a 0 byte length,

@jaswsinc I found and submitted a PR to fix that bug; see https://github.com/websharks/phings/pull/24

**Comment by jaswsinc** [comment]
I reviewed that websharks/phings PR and merged it. Great!

**Comment by raamdev** [comment]
Adding TODO item. ↑

- Update build script so that it converts all text domain references in the Lite version into string literals for translate.wordpress.org (e.g., `'zencache'` instead of `SLUG_TD` or `$this->text_domain`).

**Comment by jaswsinc** [comment]
Oooh! That's an awesome idea. I love that approach. Crafty you are :smiling_imp:

**Comment by raamdev** [comment]
@jaswsinc This PR is ready for another set of eyes when you get a chance. :-)

Things to pay particular attention to:

- Build process (Lite-generation)
- Pro Preview

**Comment by jaswsinc** [comment]
Testing now.

- _Just noting that I got the `master` branch for the `websharks/phings` repo whenver I did a fresh clone of `zencache-pro/feature/zencachecom74`, and it looks like the most recent changes are only in the `000000-dev` branch at the moment. So I'm checking out the `000000-dev` branch and running a `phing build` against the `websharks/phings` dev branch._

**Comment by raamdev** [comment]
> Just noting that I got the master branch for the websharks/phings repo whenver I did a fresh clone of zencache-pro/feature/zencachecom74,

That's odd, https://github.com/websharks/zencache-pro/commit/a27bbf2ab56849d26a653f181b2266cbe88853f5 in this PR should have bumped Phings to the correct commit.

**Comment by jaswsinc** [comment]
Cool. It was probably because I did a `git clone --recursive` instead of running it afterward in that specific branch.

**Comment by jaswsinc** [comment]
I'm reviewing the difference between the two builds now.

```bash
diff -r ~/projects/websharks/wordpress/plugins/zencache-pro/.\~build/zencache-pro/zencache-pro ~/projects/websharks/wordpress/plugins/zencache-pro/.\~build/zencache/
```

**Comment by jaswsinc** [comment]
Correction:

```bash
diff -r ~/projects/websharks/wordpress/plugins/zencache-pro/.\~build/zencache-pro/zencache-pro ~/projects/websharks/wordpress/plugins/zencache-pro/.\~build/zencache/.\~build/zencache/zencache
```

and I'm actually using `colordiff` as an alias.

**Comment by raamdev** [comment]
@jaswsinc I can do better: https://github.com/raamdev/zcpzcldiff/compare/8e6f7ef0dc8670c07c0265a8978fa550597f41fb...a9ab2b608fe4f410a9127a5ad204c3191b00ca83

**Comment by jaswsinc** [comment]
> @jaswsinc I can do better: raamdev/zcpzcldiff@8e6f7ef...a9ab2b6

Oh, that's awesome! THANK YOU.

I just skimmed over the diffs that I ran, that you ran, and I browsed through the source code in Atom. I haven't done a deep analysis myself, but I did give it a once-over to see if I could spot anything obvious. I also installed the lite build (based on the pro version) on a VM running PHP 7 + Nginx. No problems. Caching properly, no JS errors, no PHP errors, Nginx instructions look good, pro preview looks good. Regular lite interface looks good.

## We Rock!

I have a *HUGE* smile on my face dude. We just unlocked the next level of awesome with this one. I *absolutely love* the fact that we can build the lite version based on the pro version like this. How cool is that!? Next, we need to find a way to generate the pro version automatically too. LMAO

# Only thing I noticed...

`.~build/zencache/src/includes/translations/` contains:

- `zencache.pot`
- `zencache-pro.pot` ?

I think the pro POT file is misplaced there. So that might be a minor glitch in our automation awesomeness.

**Comment by raamdev** [comment]
> We Rock!
> I have a HUGE smile on my face dude. We just unlocked the next level of awesome with this one. I absolutely love the fact that we can build the lite version based on the pro version like this. How cool is that!? Next, we need to find a way to generate the pro version automatically too. LMAO

I know how you feel. :-) Every single time I run `phing` I sit back for a brief moment of reflection about the pure awesomeness (and power) that is automation. I **love** that my computer is doing all this work, on its own, the same exact way every time, and I can run it a bazillion times and it doesn't get annoyed or complain at the repetitiveness of the task. :laughing: 

Not to mention how much _time_ this saves us! We could easily handle multiple projects, each with its own RC and GA release once a month, with very few people, and have a reliable system that "just works."

> `zencache-pro.pot`?

Yep, it looks like that's an issue with the build script. Let me look into that now.

**Comment by raamdev** [comment]
@jaswsinc writes...
> `.~build/zencache/src/includes/translations/`

Actually, that's not the build directory. The build directory is `.~build/zencache/.~build/zencache/zencache`, and inside there the `src/includes/translations/zencache-pro.pot` file does not exist. So it looks like we're good?

**Comment by raamdev** [comment]
The `lite.xml` build script copies the `zencache-pro/` repo files to `.~build/zencache/`, makes some adjustments to the files, and then calls the normal build process which then builds a Lite version in `.~build/zencache/.~build/`.

The files in `.~build/zencache/` should never be considered usable or distributable; only what ends up in `.~build/zencache/.~build/` should be used/tested/distributed.

**Comment by raamdev** [comment]
(i.e., I think of `.~build/zencache/` as a staging directory for building the Lite version.)

**Comment by raamdev** [comment]
The primary reason `.~build/zencache/` should be considered a stagging area is that the final build process that generates the Lite version in `.~build/zencache/.~build/` will read additional exclusions and patterns from the `.build.props` file. If you use files in `.~build/zencache/`, those additional Lite-specific rules/routines will not have been applied to the files in `.~build/zencache/`.

**Comment by jaswsinc** [comment]
I see! Yep, no big deal. I'd say it's good-to-go.

I was just looking to see how that happens also, and once I reviewed what you said above, I was trying to figure out how it magically dissappears once the build is complete. Now I see that you have it listed in the project-specific exclusions via the `.build.props` file.

```
project_other_zip_tgz_fileset_exclusions           = README.md, **/AutoCache.php, **/AutoCacheUtils.php, **/CdnFilters.php, **/CdnUtils.php, **/WcpCdnUtils.php, **/cdn-filters.txt, **/HtmlCUtils.php, **/WcpHtmlCUtils.php, **/StatsUtils.php, **/WcpEvalUtils.php, **/WcpS2cleanUtils.php, **/WcpTransientUtils.php, **/WcpUrlUtils.php, **/WcpUserUtils.php, **/MenuPageProUpdater.php, **/MenuPageStats.php, **/DirStats.php, **/admin-bar*.js, **/AdminBarUtils.php, **/options-pro.png, **/pro-updater.png, **/stats*.png, **/zencache-pro.pot
```

So it's a minor bug in the build script, but not a huge deal. We just need to delete the pro POT file whenever we copy the directory, or rename it to the lite slug somewhere around this area. https://github.com/websharks/phings/blob/000000-dev/src/psr4/targets/lite.xml#L45

**Comment by jaswsinc** [comment]
> The primary reason .~build/zencache/ should be considered a stagging area is that the final build process that generates the Lite version in .~build/zencache/.~build/ will read additional exclusions and patterns from the .build.props file. If you use files in .~build/zencache/, those additional Lite-specific rules/routines will not have been applied to the files in .~build/zencache/.

I agree. It's a staging area. However, that directory does form the basis for what a lite repo might look like, should we ever want to do that, and it also serves as the base for what is ultimately packaged-up and shipped as the zip file. The `packages.xml` file in the websharks/phings repo will work from that directory; i.e., during the lite build process, `${project.basedir}` (when building the lite version) is actually: `.~build/zencache/`

**Comment by raamdev** [comment]
Or we could just add the `${project_lite_other_zip_tgz_fileset_exclusions}` to [this section](https://github.com/websharks/phings/blob/160107/src/psr4/targets/lite.xml#L27-L31), so those files don't get copied in the first place, right?

**Comment by jaswsinc** [comment]
> Or we could just add the ${project_lite_other_zip_tgz_fileset_exclusions} to this section, so those files don't get copied in the first place, right?

Yep, that would work too. Although, since POT generation is a part of the build process itself; i.e., it is solely responsible for the generation of those files to begin with, I don't think it should require additional configuration in `.build.props` for this to work. I like where you're going with that idea though.

Perhaps just adding this line to the list of [exclusions there](https://github.com/websharks/phings/blob/000000-dev/src/psr4/targets/lite.xml#L29).

```xml
<exclude pattern=".~build/**" />
<exclude pattern="src/includes/translations/${project_slug}.pot" />
```
```

**Comment by raamdev** [comment]
> Or we could just add the ${project_lite_other_zip_tgz_fileset_exclusions} to this section, so those files don't get copied in the first place, right?

Or maybe not.

`.~build/zencache/` should reflect what the `zencache-pro/`repo looks like prior to being built. It's during the `-lite` portion of the build process that `.~build/zencache/` gets converted into a Lite version of the plugin to be built.

`${project_lite_other_zip_tgz_fileset_exclusions}` are specifically for the Lite distribution build part of the build process. If we applied those exclusions to where we copy files from the `zencache-pro/`repo, then what ends up in `.~build/zencache/` _would not_ be reflective of what the `zencache-pro/`repo looks like prior to being built.

> ```
<exclude pattern="src/includes/translations/${project_slug}.pot" />
```

I don't like that because that doesn't take into consideration changes in the path to translations for each project. It assumes that every project that uses the build process will use `src/includes/translations/`.

**Comment by raamdev** [comment]
How about this?

```
<exclude pattern="**/**-pro.pot" />
```

**Comment by jaswsinc** [comment]
> It assumes that every project that uses the build process will use src/includes/translations/

That's a safe assumption, because the build script has this hard-coded already, and this is a part of the PSR4 standard that this particular build routine follows. So any project that uses this phing should follow that standard IMO. The full path to the translations dir is not a part of the official PSR-4 standard, only `src/` portion is, but the rest of the path is a part of a standard that we set in the build script itself.

Referencing: https://github.com/websharks/phings/blob/000000-dev/src/psr4/targets/pots.xml

**Comment by jaswsinc** [comment]
> <exclude pattern="**/**-pro.pot" />

That works for me.

**Comment by raamdev** [comment]
@jaswsinc Thanks for the help reviewing here. Anything else before I merge this in? I'm not going to merge it until tomorrow morning so take your time if you have any more testing you'd like to do. :-)

**Comment by jaswsinc** [comment]
No problems found so far. Looks great to me. :shipit:

**Comment by raamdev** [comment]
> No problems found so far. Looks great to me.

Awesome. Thank you!

**Pull request closed without merging**
