### PR TITLE
Convert line-delimited patterns to a regex; See: websharks/zencache#191

### PR DESCRIPTION
**Pull request by kristineds**
Convert line-delimited patterns to a regex.
- Enhancing exclusion patterns

See: websharks/zencache#191

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting PR for Step 1.

**Comment by jaswsinc** [comment]
Woohoo! Looks good to me.

**Comment by jaswsinc** [comment]
@raamdev I suggest waiting until Step 2 is complete, and then merge this in.

**Comment by jaswsinc** [comment]
@raamdev ~ @kristineds Once you complete work on step 2 of this issue PR I will come back in before it is merged in and add support for this new technique so that it works in a list of Custom URLs too. Referencing Raam's comment here: https://github.com/websharks/zencache-pro/pull/159#issuecomment-148785648

**Comment by raamdev** [comment]
> Once you complete work on step 2 of this issue PR I will come back in before it is merged in and add support for this new technique so that it works in a list of Custom URLs too. Referencing Raam's comment here: #159 (comment)

@jaswsinc Noting here that @kristineds added a note about Wild Cards **not** being supported in the Custom URLs box (see https://github.com/websharks/zencache-pro/commit/746b27b1cd0faee3830238c35726ae7f4aa382b2), so that line needs to be removed once support for wildcards _is_ added.

**Comment by raamdev** [comment]
@jaswsinc This PR can be closed now that https://github.com/websharks/zencache-pro/pull/163 has been merged, correct?

**Comment by jaswsinc** [comment]
Correct.

**Pull request closed without merging**
