### PR TITLE
Add hourly option on `purge_cache()` method; See: websharks/zencache#472

### PR DESCRIPTION
**Pull request by kristineds**
Add hourly option on `purge_cache()` method; 

- This is Step 1 of 2. _Note: Don't merge yet until step 2 has been completed_
- Adding functionality for hourly option on `purge_cache()` method

See: websharks/zencache#472

### CODE REVIEW

**Comment by jaswsinc** [comment]
@raamdev I am seeing a minor problem in this PR. I'll come back to this shortly and explain. It's nothing that Kristine introduced, but it looks like there is a minor bug in the existing release and we can knock that out as part of the work being done on this PR. More to come shortly...

**Comment by jaswsinc** [comment]
## @kristineds Next Actions

- In [this line](https://github.com/websharks/zencache-pro/blob/c0f275848d794387860c456b5cfe0a932b2ae9c3/src/includes/classes/Plugin.php#L525) change `__NAMESPACE__` to `GLOBAL_NS` please.

**Comment by kristineds** [comment]
@jaswsinc That has been updated. :+1:  https://github.com/websharks/zencache-pro/commit/6ac79e9b8b055061be1f378e5d534ab6d7ef01ad

**Comment by jaswsinc** [comment]
@kristineds Perfect. Thanks!

@raamdev Kristine's [last commit](https://github.com/websharks/zencache-pro/commit/6ac79e9b8b055061be1f378e5d534ab6d7ef01ad) improves this PR and also resolves [this bug](https://github.com/websharks/zencache/issues/613#issuecomment-157302333).

**Comment by raamdev** [comment]
@jaswsinc I'm not seeing that this is configurable (as discussed [here](https://github.com/websharks/zencache/issues/472#issuecomment-101350168)). Can we at least make the schedule filterable?

**Comment by raamdev** [comment]
@jaswsinc Sorry, I jumped the gun. :-) I didn't see that [Step 2](https://github.com/websharks/zencache/issues/472#issuecomment-156088477) had not yet been completed.

**Comment by raamdev** [comment]
Oh, it has been finished, but in a separate PR: https://github.com/websharks/zencache-pro/pull/180

**Comment by raamdev** [comment]
Merged. Thank you, @kristineds! :-)

**Pull request merged**
