### PR TITLE
PR: feature/502

### PR DESCRIPTION
**Pull request by jaswsinc**
See: websharks/zencache#502

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc The part of this PR that uses the Product API to check for the latest Lite version _might_ cause problems with the WordPress.org rules to not "phone home" without explicitly checking with the site owner first. That was why I had [suggested](https://github.com/websharks/zencache/issues/502#issuecomment-158818855) that we don't bother with detecting the latest Lite version in the Options menu.

**Comment by jaswsinc** [comment]
Well, we can just explain that it's not a phone, it's a TCP connection. ha. No, I get ya. I'll disable that part shortly and update this PR. Thanks for the review.

**Comment by raamdev** [comment]
@jaswsinc changing this to `in progress` until the above changes are committed. :-)

**Comment by jaswsinc** [comment]
@raamdev Tweaked as suggested. Please review when you get a moment. Thanks!

**Comment by jaswsinc** [comment]
@raamdev Note: the `phings` repo commit sha seems to have changed from the dev branch in this PR. Hopefully you know what that should _actually_ be and can change it on your end. If not, just let me know what you'd like me to do in order to change that. See: https://github.com/websharks/zencache-pro/commit/9b54a298ea7bf64c251667697733125fec6e9573

**Comment by raamdev** [comment]
@jaswsinc Only one correction I made: https://github.com/websharks/zencache-pro/commit/30a6048477f0e82ccd5a81255c40615cbfb7b993 Otherwise looks great. Thanks! :-)

**Comment by raamdev** [comment]
Tested and confirmed working in Lite version:

**Comment by jaswsinc** [comment]
:+1:

**Pull request closed without merging**
