### PR TITLE
Improve HTML notes messaging when s2Member is installed.

### PR DESCRIPTION
**Pull request by renzms**
See: websharks/zencache#504

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc I reviewed this and it looks good to me. I'll merge this once you concur.

**Comment by raamdev** [comment]
@renzms In the description of this PR and in the commit message I think you meant websharks/zencache#504 not websharks/zencache-pro#504. :smile:

**Comment by renzms** [comment]
@raamdev 

Ah, you're right! Thanks! haha

**Comment by jaswsinc** [comment]
@raamdev Looks good to me! @renzms Nice work!

**Comment by raamdev** [comment]
@renzms Merged. Thanks! :-)

**Pull request merged**
