### PR TITLE
Feature/191 Step 3

### PR DESCRIPTION
**Pull request by jaswsinc**
Includes changes from: 

- https://github.com/websharks/zencache-pro/pull/155
- and changes introduced in the first draft of: https://github.com/websharks/zencache-pro/pull/162

---

- Includes additional changes that add support for `*`, `**`, `^`, and `$` in a list of custom URLs.
- Includes additional changes that add support for `*`, `**`, `^`, and `$` in calls to the new API Function: `zencache::clearUrl($url)`
- Improves support for `*`, `**`, `^`, and `$` in Sitemap URIs that should be cleared also.

### CODE REVIEW

**Comment by jaswsinc** [comment]
@raamdev This is ready to be reviewed/merged now.

_**Note:** Please merge this PR instead of https://github.com/websharks/zencache-pro/pull/155, as this one includes all of the changes from that PR and then some._

---

Step 2 (i.e., inline documentation updates) are still being worked on in https://github.com/websharks/zencache-pro/pull/162

**Comment by raamdev** [comment]
@jaswsinc Cool! I'll start testing and reviewing this now. :-)

**Comment by raamdev** [comment]
Tested `^/$`, `*`, and `**` with Custom URLs. All working as expected! Awesome! :100:  :-)

**Comment by raamdev** [comment]
@jaswsinc Just to confirm, this can be merged into `000000-dev` despite #162 not being finished yet, correct?

**Comment by jaswsinc** [comment]
I should note that any custom URLs that are listed (to be cleared automatically) are taken almost literally. Therefore, in a Multisite Network you will need to list URLs that you want to exclude, not URIs that apply to every site in the network. I think that's desirable anyway.

The same is true for domain mapping. If you want to clear URLs for a mapped domain, the URLs that you list should include the mapped domain.

With all of that being said, since wildcards are supported, you can also do something like this to cover all domains if you need to:

```
http://*/path/to/something/
```

**Comment by jaswsinc** [comment]
The scheme (i.e., `http://` or `https://` is ignored), and both schemes are cleared automatically.

**Comment by jaswsinc** [comment]
> Just to confirm, this can be merged into 000000-dev despite #162 not being finished yet, correct?

Yep :-) Great!

**Comment by raamdev** [comment]
@jaswsinc @kristineds Merged! Thanks! :-)

**Pull request merged**
