### PR TITLE
Update inline documentation for new syntax; See: websharks/zencache#191

### PR DESCRIPTION
**Pull request by kristineds**
Update inline documentation for new syntax; 
- _A wildcard `*` character can also be used when necessary; e.g., `/xy*-framework/` (where `*` = 0 or more characters that are NOT a slash `/`). Other special characters include: `**` = 0 or more characters of any kind, including `/` slashes; `^` = beginning of the string; `$` = end of the string. To learn more about this syntax, please see [this KB article](http://zencache.com/r/watered-down-regex-syntax/)._

See: websharks/zencache#191

### CODE REVIEW

**Comment by kristineds** [comment]
@raamdev @jaswsinc Submitting PR for updating the inline documentation to include new syntax that Jason mentioned https://github.com/websharks/zencache-pro/pull/162#issuecomment-149772043

Here is the link to the drafted KBA (still work in progress) for Watered Down Regex Syntax : https://github.com/websharks/zencache-kb/issues/94

**Comment by raamdev** [comment]
@kristineds It looks like we still need to update the inline docs for the new Custom URLs feature, as that currently says wildcards are not supported when in fact they now _are_ supported (via the watered down syntax). See my note [here](https://github.com/websharks/zencache-pro/pull/155#issuecomment-149378955).

**Comment by kristineds** [comment]
@raamdev That line has been removed. https://github.com/websharks/zencache-pro/commit/f1539136e349726f4a676a84fa26d6f40a9a49c3

**Comment by raamdev** [comment]
@kristineds writes ([on Slack](https://websharks.slack.com/archives/zencache/p1445493549000048))... 
> Will I be updating the inline documentation for Auto-Clear a List of Custom URL with the exact documentation that I did for those made on URI Exclusion Patterns regarding the new syntax?
> 
> i.e.  ​_A wildcard `*` character can also be used when necessary; e.g., `/xy*-framework/` (where `*` = 0 or more characters that are NOT a slash `/`). Other special characters include: `**` = 0 or more characters of any kind, including `/` slashes; `^` = beginning of the string; `$` = end of the string. To learn more about this syntax, please see [this KB article](http://zencache.com/r/watered-down-regex-syntax/)._​

I believe the answer is yes, as that wildcard syntax is now supported by the Custom URLs feature. Is that correct @jaswsinc?

**Comment by jaswsinc** [comment]
> I believe the answer is yes, as that wildcard syntax is now supported by the Custom URLs feature. Is that correct @jaswsinc?

That is correct, yes.

**Comment by kristineds** [comment]
@raamdev @jaswsinc Submitted new PR to include documentation on new syntax. (https://github.com/websharks/zencache-pro/commit/44cfb1f3feb94809ca91280b817257e49f5fcc70)

- _A wildcard `*` character can also be used when necessary; e.g., `/category/abc-followed-by-*` (where `*` = 0 or more characters that are NOT a slash `/`). Other special characters include: `**` = 0 or more characters of any kind, including `/` slashes; `^` = beginning of the string; `$` = end of the string. To learn more about this syntax, please see [this KB article](http://zencache.com/r/watered-down-regex-syntax/)._

**Comment by raamdev** [comment]
@kristineds Looks great! Thank you. Merged!

**Pull request merged**
