### PR TITLE
Strip whitespace from contents of wp-config.php when checking WP_CACHE

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/zencache#591

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc Review please. I tested this and it's working as expected when enabling/disabling ZenCache.

**Comment by raamdev** [comment]
Thinking this over some more, it's probably less confusing to only modify the `preg_match()` line and pass in `php_strip_whitespace($wp_config_file)` instead of `$wp_config_file_contents`.

That way we can leave `if (!($wp_config_file_contents = file_get_contents($wp_config_file))) {` alone. I was modifying that line because I was thinking of the performance hit reading the file twice, but that's not really an issue here (as this is only run when enabling/disabling ZenCache).

**Comment by jaswsinc** [comment]
Nice! Yeah, I agree with your thoughts on there being a separate call to read the file like that.

**Comment by raamdev** [comment]
> I agree with your thoughts on there being a separate call to read the file like that.

So you think it should remain as-is, or I should change things by moving the `php_strip_whitespace()` call to `preg_match()`?

**Comment by jaswsinc** [comment]
> So you think it should remain as-is, or I should change things by moving the php_strip_whitespace() call to preg_match()?

I would create a second variable with a duplicate block like this one. See: https://github.com/websharks/zencache-pro/blob/be0a44af033adc05e3f3074e58ac1381e76d29ee/src/includes/closures/Plugin/InstallUtils.php#L137-L139

One block for `$wp_config_file_contents` and another for `$wp_config_file_contents_no_whitespace`. That way you are checking if `$wp_config_file_contents_no_whitespace` is empty also, and you can use `$wp_config_file_contents_no_whitespace` in your `preg_match()` test.

**Comment by raamdev** [comment]
> You could do this on both of these lines also. See: https://github.com/websharks/zencache-pro/blob/be0a44af033adc05e3f3074e58ac1381e76d29ee/src/includes/closures/Plugin/InstallUtils.php#L185-L188

Can't do it there because that would end up writing the whitespace-stripped version of `wp-config.php` back to the file...

I did make a few improvements as you suggested though; see https://github.com/websharks/zencache-pro/commit/639a7ad7cc7e7a9b7e8c1cb795293bb9d3453db4. How's that look?

**Comment by jaswsinc** [comment]
> see 639a7ad. How's that look?

Looks great to me! :-)

> You could do this on both of these lines also. See: https://github.com/websharks/zencache-pro/blob/be0a44af033adc05e3f3074e58ac1381e76d29ee/src/includes/closures/Plugin/InstallUtils.php#L185-L188
> Can't use it in the preg_replace() call because that would end up writing the whitespace-stripped version of wp-config.php back to the file...

I was referring the `\b` in front `define` there.

**Comment by raamdev** [comment]
> I was referring the \b in front define there.

Oh, whoops, didn't notice that was a commit comment. :-) Done: https://github.com/websharks/zencache-pro/commit/cea249bce6dd9ce77db538bf0757f240238d5bce

**Comment by jaswsinc** [comment]
Awesome. Looks ready to merge to me.

**Comment by raamdev** [comment]
Thanks! :-)

**Pull request closed without merging**
