### PR TITLE
Feature/68 :: Network Cache Clearing Roles/Caps

### PR DESCRIPTION
**Pull request by jaswsinc**
One commit: https://github.com/websharks/zencache-pro/commit/e73a44782a7a04ae7f15d88a6d3f0b3ffbcc16ef accomplishes the following:

- This PR adds the feature requested in https://github.com/websharks/zencache/issues/68
- Also enhances the UI just a bit.
  - Separating Manual Cache Clearing from Automatic Cache Clearing.
    - Placing each set of automatic cache clearing options under its own sub-heading.
  - Adding section-specific icons to more easily identify each set of config. options.
  - Adding option to enable stats for child site owners.
- Includes changes from websharks/zencache-pro#127

---

---

---

### CODE REVIEW

**Comment by jaswsinc** [comment]
This is ready for another pair of eyes.

**Comment by jaswsinc** [comment]
@raamdev writes in websharks/zencache#68

> Removing "Multisite" from the title of this Feature Request, as this feature would be relevant to both multisite and non-multisite installs.

I missed that the first time around. Well, we have multisite compat. in there for now.

**Comment by jaswsinc** [comment]
Standard installs have been covered now also. See: https://github.com/websharks/zencache-pro/pull/132

**Comment by raamdev** [comment]
@jaswsinc Awesome! Looks great! I love the section-specific icons. Merged.

**Comment by jaswsinc** [comment]
Cool. That's great!

**Pull request merged**
