### PR TITLE
Add unique key to BEGIN/END comment blocks in .htaccess

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/zencache#620

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc A review here, please. Here's the regex on regex101.com that I'm using in this PR: https://regex101.com/r/vZ3rN0/1

**Comment by jaswsinc** [comment]
Awesome! I just reviewed the code and regex. Here's are my thoughts.

- The end of your regex has `.*\s*`, and that `.*` is a problem. It will eat up anything after and until the end of the entire file, because of the `/s` flag; i.e., `.` dot matches newlines too, and it is greedy.

- I think the regex could be simpler if the marker is used exclusively as the start and end points, instead of it being a part of something more in terms of how of we search/replace.

  See possible alternative here: https://regex101.com/r/vZ3rN0/2
  
  Summary of Changes:

  - Strip the `=`, which is not required to properly decode base64.
  - Use `WmVuQ2FjaGU` as the open tag (like HTML), and `/WmVuQ2FjaGU` as the close tag (like HTML).
  - Simplify regex: `#\s*WmVuQ2FjaGU.*?\/WmVuQ2FjaGU\s*/s`
  - Drop the `/i` flag, because base64 is case sensitive.

**Comment by raamdev** [comment]
> Use WmVuQ2FjaGU as the open tag (like HTML), and /WmVuQ2FjaGU as the close tag (like HTML).

Hmm, it would look a lot more readable if the comment started with `# BEGIN ZenCache`. Also, I was trying to make those comments _a little_ flexible, in case a site owner wanted to clean up his/her `.htaccess` file and maybe just use ` # BEGIN ZenCache WmVuQ2FjaGU`. I agree with all the other points--thank you!

**Comment by jaswsinc** [comment]
> Hmm, it would look a lot more readable if the comment started with # BEGIN ZenCache. Also, I was trying to make those comments a little flexible

I see. Yeah, I agree. Well, since `#` is also a required part of the marker, we could just alter it slightly so that the open tag is actually `#.*?WmVuQ2FjaGU`. That way the open tag could be:

```
#[ANYTHING]WmVuQ2FjaGU
```

**Comment by jaswsinc** [comment]
I think what is most important is that `/WmVuQ2FjaGU` be the very end.

**Comment by raamdev** [comment]
> I think what is most important is that /WmVuQ2FjaGU be the very end.

What's the importance of `/`? Why couldn't we use `# END[anything]WmVuQ2FjaGU[whitespace]`?

**Comment by jaswsinc** [comment]
Thats works too, so not important if you use `END` as the end marker.

My thought was that, since we are now using a unique marker instead of a specific phrase, the `/` could be used instead of a word like `END`. Thus, `/WmVuQ2FjaGU` would suffice, where `/` is used together with the marker so that a site owner could alter the words `BEGIN` and `END` without damaging anything.

**Comment by raamdev** [comment]
Right, but `BEGIN` and `END` are far more common as markers, both in HTML comments and in `.htaccess` files (other plugins that write to the `.htaccess` file also use `BEGIN/END`.

**Comment by jaswsinc** [comment]
You could still type those in there for clarity so that they appear in the `.htaccess` file, but because we are using a unique marker, which other plugins that _only_ use `BEGIN` and `END` do not have, we can get away with something a bit more elegant. In our case, the marker is not `BEGIN` `END`, the _real_ marker is `WmVuQ2FjaGU`, which uniquely identifies the automated portion of the `.htaccess`, to help separate it from anything that a site owner adds on their own.

So my feeling is that if `WmVuQ2FjaGU` is the _real_ marker, that, and only that (if possible), is what our regex should be looking for IMO; i.e., `WmVuQ2FjaGU` (open) and `/WmVuQ2FjaGU` (close), as an example. Or you could think about it like this, and maybe this is even better for clarity.

```
# <WmVuQ2FjaGU>
  Whatever here...
# </WmVuQ2FjaGU>
```

**Comment by raamdev** [comment]
I hear your point, and from a programatic perspective that makes more sense. But from a readability perspective (which is what comments are designed for), it makes more sense to clearly indicate "this is where something begins and this is where something ends". Using an HTML style format inside a comment inside an `.htaccess` file is _confusing_ to say the least. Using a `/WmVuQ2FjaGU` is also confusing because then there's a question about whether the unique marker is `WmVuQ2FjaGU` or `/WmVuQ2FjaGU`.

All of that is resolved by following the informal style of `# BEGIN` and `# END`, including the name of the plugin (`ZenCache`) and including the unique marker `WmVuQ2FjaGU`. I would also include in the comment a note explaining that `WmVuQ2FjaGU` _is_ a unique marker required for the plugin to identify that codeblock (as in my original commit), because again, comments are designed to be human readable and informative. I don't think it should be _required_ to have that descriptive text in the codeblock, which is why I suggest we only require `#` `BEGIN/END`, `ZenCache`, and `WmVuQ2FjaGU` on the comment lines.

**Comment by jaswsinc** [comment]
> All of that is resolved by following the informal style of # BEGIN and # END, including the name of the plugin (ZenCache) and including the unique marker WmVuQ2FjaGU. I would also include in the comment a note explaining that WmVuQ2FjaGU is a unique marker required for the plugin to identify that codeblock (as in my original commit), because again, comments are designed to be human readable and informative. I don't think it should be required to have that descriptive text in the codeblock, which is why I suggest we only require # BEGIN/END, ZenCache, and WmVuQ2FjaGU on the comment lines.

No objection. Sounds fine to me :-) I've heard it both ways. haha

**Comment by raamdev** [comment]
@jaswsinc How's this? https://regex101.com/r/vZ3rN0/4

We can require the following format as a minimum:

```
# BEGIN ZenCache WmVuQ2FjaGU

# END ZenCache WmVuQ2FjaGU
```

An additional comment after the unique string explaining not to remove the unique string can be added by the plugin, i.e., 

```
# BEGIN ZenCache WmVuQ2FjaGU (do not remove WmVuQ2FjaGU marker)
```

**Comment by raamdev** [comment]
Also, for usability reasons, I would make that regex case `i`nsensitive. Accepting `# begin zencache wmvuq2fjagu` should be OK too, IMO. But I'm fine with keeping it case-sensitive if you prefer that.

**Comment by jaswsinc** [comment]
Looks great to me!

> Also, for usability reasons, I would make that regex case insensitive. Accepting # begin zencache wmvuq2fjagu should be OK too, IMO. But I'm fine with keeping it case-sensitive if you prefer that.

Agree, caSe-insensitive does sound better.

I wonder if it would help others to recognize `WmVuQ2FjaGU` as being a marker if it was encapsulated in some way. At the moment, it's just hanging out all by itself. Do you think wrapping it with something like `<WmVuQ2FjaGU>` or `{WmVuQ2FjaGU}` would make any difference?

**Comment by raamdev** [comment]
My feeling is that encapsulating it distorts _what_ the unique key actually is (does it include `[` and `]`?), whereas surrounding it by space characters sort of clarifies that.

I would use the following as the first comment:

```
# BEGIN ZenCache WmVuQ2FjaGU (the WmVuQ2FjaGU marker is required for ZenCache; do not remove)
```

**Comment by jaswsinc** [comment]
Copy. Looks nice.

**Comment by raamdev** [comment]
@jaswsinc ↑ Review please.

**Comment by jaswsinc** [comment]
Cool. I just took another look at this and I have one more suggestion and a question.

- I suggest generating `WmVuQ2FjaGU` based on `NAME`, so that whenever the software is rebranded that marker will change. Does sound sound right? e.g., `$marker = trim(base64_encode(NAME), '=')`

- What happens whenever you already have the old snippet (without the marker), and then you upgrade from one version of the software to the next? As it exists at the moment, it looks like the old snippet (without the marker) would _not_ be removed, and yet the new one will be added on top of the old one.

**Comment by raamdev** [comment]
> I suggest generating WmVuQ2FjaGU based on NAME, so that whenever the software is rebranded that marker will change. Does that sound right? e.g., $marker = trim(base64_encode(NAME), '=')

Agreed.



> What happens whenever you already have the old snippet (without the marker), and then you upgrade from one version of the software to the next? As it exists at the moment, it looks like the old snippet (without the marker) would not be removed; i.e., error during reactivation.

Thanks for reminding me about that (I had thought of that issue while working on this but then forgot about it). Yeah, the way I see it we have two options:

- Strip out any existing `# BEGIN ZenCache` block, thereby risking us deleting custom code where someone else used the same comment marker (this is the current bug we're trying to fix).
- OR, leave any existing `# BEGIN ZenCache` block, thereby risking us duplicating the code we're inserting (their `.htaccess` could end up with two blocks of code that were added by ZenCache).

My vote is that we look for a _very specific_ block of code to narrow down what ZenCache v151114 may have added, i.e.,

```
# BEGIN ZenCache

<IfModule headers_module>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>

# END ZenCache
```

If we find that specific block of code, with that specific `.htaccess` rule, _then_ we remove it and insert our block that includes the unique key.

**Comment by raamdev** [comment]
We should also look for and remove this from the `.htaccess` file, which is what ZenCache v151114 would've added if you enabled Static CDN Filters and then disabled them:

```
# BEGIN ZenCache
# END ZenCache
```

**Comment by jaswsinc** [comment]
> My vote is that we look for a very specific block of code to narrow down what ZenCache v151114 may have added, i.e.,

Ah, cool. Yep, that sounds like a good plan to me also.

**Comment by raamdev** [comment]
> I suggest generating WmVuQ2FjaGU based on NAME, so that whenever the software is rebranded that marker will change. Does that sound right? e.g., $marker = trim(base64_encode(NAME), '=')

Actually, I was just thinking about this and maybe this _doesn't_ make sense. Why would we want a different marker if the name of the plugin changes? That will just mean we'll need to write upgrade routines that look for and remove the old blocks and then re-add them using the new unique marker. That seems like we're adding unnecessary code if we'll need to strip out those old blocks anyway to change the name of the plugin in those comment blocks.

If we leave the marker the same, then the only thing we need to do when changing the name of the plugin is to add 3 extra lines to `removeWpHtaccess()` that also looks for and removes the blocks that contain the old plugin name. It makes no difference if the unique marker is the same.

**Comment by jaswsinc** [comment]
I see your point. Hard to predict exactly what would work best whenever we start on the rebranding, but I inclined to agree with you. Sounds like having just one would be better.

**Comment by raamdev** [comment]
@jaswsinc  Another review please. ↑ I added an upgrade routine that will remove the old comment blocks as discussed above and I tested this code to confirm it works as expected when upgrading with either template scenario in place (empty or with the `Access-Control-Allow-Origin` code inside).

**Comment by jaswsinc** [comment]
I haven't tested this yet, but I did review the code. Looks great!

Couple of observations...

- In `fromLte151114()`, the `return true;` and `return false;` lines could just be `return;`, because there is no need for the version-specific upgrade routines to return a boolean value, or return anything at all for that matter. A `return;` is the same as `return null;`, and that's what is expected from those routines.

- I wouldn't change anything else since you've already put in the work to test all of this. However, in the future you might consider putting verbatim data that you're going to search for in a text file, to keep it separate. It's less prone to corruption that way, and it keeps the codebase cleaner, since you won't need to single quote and wrap lines against the leftmost margin to get what you need.

  Also, you could just use `str_replace()` instead of `preg_replace()` whenver you're doing string-for-string search/replace. There is nothing wrong with using `preg_replace()`, but it's not really necessary in this instance either.

  ```php
  $htaccess_contents = str_replace(file_get_contents('find-this.txt'), '', $htaccess_contents);
  ```

**Comment by raamdev** [comment]
Great feedback. Thank you. 

> you might consider putting verbatim data that you're going to search for in a text file

Where would you put such a text file? `src/includes/templates/htaccess/v151114.txt` and `v151114-2.txt`?

**Comment by jaswsinc** [comment]
Yep, that looks good. Or, maybe inside a sub-directory that marks it as something old.

```
src/includes/templates/htaccess/back-compat/v151114.txt
```

**Comment by raamdev** [comment]
@jaswsinc One more review, please. ↑ I tested the refactored code and it's working great.

**Comment by jaswsinc** [comment]
Niiiice! :-) :heart_eyes: Love it.

**Pull request closed without merging**
