### PR TITLE
Step 2 - Feature Request: URI Exclusion Patterns for Client-Side Cache

### PR DESCRIPTION
**Pull request by renzms**
see websharks/zencache#498

### CODE REVIEW

**Comment by jaswsinc** [comment]
Reviewed. I left you a comment here https://github.com/websharks/zencache/issues/498#issuecomment-159090072

**Comment by raamdev** [comment]
@jaswsinc Between https://github.com/websharks/zencache-pro/pull/182 and this PR, does this look ready to merge?

**Comment by jaswsinc** [comment]
- Step 1 looks great to me.
- Step 2 is shaping up, but it could use a critique from @raamdev now I think. See latest revision here: https://github.com/websharks/zencache/issues/498#issuecomment-159591504

**Comment by raamdev** [comment]
@jaswsinc writes...
> Step 2 is shaping up, but it could use a critique from @raamdev now I think. See latest revision here: websharks/zencache#498 (comment)

Thank you for that status update. :-) I reviewed the work thus far and left some feedback for Renz here: https://github.com/websharks/zencache/issues/498#issuecomment-159713315

**Comment by raamdev** [comment]
@renzms Thank you! Looking great. :-) Here's some more feedback (regarding https://github.com/websharks/zencache/issues/498#issuecomment-159848588):

- [ ] Please change your current description of this new section to the following: "When you enable Client-Side Caching above, you may want to prevent certain pages on your site from be cached by a client-side browser. This is where you will enter those if you need to (one per line)."
- [ ] Take a look at the description in the URI Exclusion Patterns options panel. Please copy the sentence that starts with "Searches are performed against the `REQUEST_URI`;" and everything after it, and add that to the description of Client-Side Caching Exclusion Patterns.
- [ ] Please change "Client-Side Caching Exclusion Patterns" to "Exclusion Patterns for Client-Side Caching". (I realized the title flows better that way and its better to start with the 'exclusion patterns' as that's the purpose of that section.)

Also, please post screenshot updates inside the PR and not on the original GitHub Issue, that way the original GitHub issue doesn't get filled up with us going back and forth with feedback on the PRs. :-) I made the mistake of providing you feedback inside the original GitHub issue because that's where I saw your screenshot, so that's partly my fault.

**Comment by renzms** [comment]
plugin options renz s test area wordpress 3

@raamdev 
Tested and submitting PR. Thanks!

**Comment by raamdev** [comment]
@renzms Merged. Thank you! :smile:

**Pull request merged**
