### PR TITLE
Clear cache for specific URL; See: websharks/zencache#590

### PR DESCRIPTION
**Pull request by kristineds**
Clear cache for specific URL; 
- Add new API Function that would allow a site owner to clear the cache for a specific URL
- Add `zencache::clearUrl($url);`

See: websharks/zencache#590

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting pull request to add `zencache::clearUrl($url);` API function

**Comment by raamdev** [comment]
Thanks @kristineds! :-)

@jaswsinc Looks good to me. I'll merge once you get a chance to review.

**Comment by jaswsinc** [comment]
Looks good to me! Nice work @kristineds

**Comment by raamdev** [comment]
Merged! Thank you @kristineds. :-)

**Pull request merged**
