### PR TITLE
Automatically clears cache files for a custom list of URLS; See: websharks/zencache#111

### PR DESCRIPTION
**Pull request by kristineds**
Automatically clears cache files for a custom list of URLS; 
-  Could specify a custom list of URIs that should be purged when a post is published/modified

See: websharks/zencache#111

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting pull request for feature request:  User-defined URIs to purge with post cache

**Comment by jaswsinc** [comment]
@kristineds Nice work. This looks good to me.

**Comment by raamdev** [comment]
@kristineds Thank you!

I noticed the new **Auto-Clear a List of Custom URLs Too?** option appears to be listed under the **Sitemap-Related Options** section, which is not correct. 



There should be a new `<hr>` and new `<h3>` heading (like Sitemap-Related Options) called **Misc. Auto-Clear Options** that makes it clear the new option is not part of the Sitemap-Related Options:


 
---

@jaswsinc By looking at the code it appears that wildcards and regex patterns are _not_ supported in this list of Custom URLs to auto-clear, is that correct? If so, @kristineds we should add a note after "Please list one URL per line." that clarifies this: "(Note that wildcards and RegEx's are **not** supported here.)"

**Comment by raamdev** [comment]
Also noting here that supporting wildcards in this Custom URLs to auto-clear box would make this feature solve various other scenarios and really increase the power of this feature. See https://github.com/websharks/zencache/issues/111#issuecomment-133766571

Thoughts @jaswsinc?

**Comment by jaswsinc** [comment]
> supporting wildcards in this Custom URLs

Agreed. My suggestion would be to exclude that from this PR (i.e., after Kristine makes the changes you suggested above, go ahead and merge it). Then we can make the regex enhancement a part of the work being done in this other PR instead. See: https://github.com/websharks/zencache-pro/pull/155#issuecomment-148803566

That way it will support the new improved flavor as well.

**Comment by raamdev** [comment]
> My suggestion would be to exclude that from this PR (i.e., after Kristine makes the changes you suggested above, go ahead and merge it). Then we can make the regex enhancement a part of the work being done in this other PR instead. See: #155 (comment)

Sounds great! Thanks! :smiley:

**Comment by kristineds** [comment]
@raamdev @jaswsinc Re-submitting PR which includes the following: https://github.com/websharks/zencache-pro/commit/746b27b1cd0faee3830238c35726ae7f4aa382b2
- Add new heading Misc. Auto-Clear Options 
- Add text: `(Note that wildcards and RegEx's are **not** supported here.)`

**Comment by raamdev** [comment]
@kristineds Perfect! Thanks so much. :-) Merged!

**Pull request merged**
