### PR TITLE
Create wipeCdnCache() and clearCdnCache() methods; See: websharks/zencache#488

### PR DESCRIPTION
**Pull request by kristineds**
Create wipeCdnCache() and clearCdnCache() methods

See: websharks/zencache#488

### CODE REVIEW

**Comment by jaswsinc** [comment]
@raamdev Just wanted to note that this work is incomplete at the moment; i.e., one step of some others that will follow. However, you could go ahead and merge this if you want to, as it will not hurt anything so far as I can see.

**Comment by raamdev** [comment]
> Just wanted to note that this work is incomplete at the moment;

Copy that. Thanks for the heads up! :-)

**Comment by jaswsinc** [comment]
https://github.com/websharks/zencache-pro/commit/b91e0694c248ac7a6c369e61174cf4fd3b82dff2 includes some minor tweaks from me. With these tweaks I am clearing a path for the next steps that I'll document for Kristine in a few minutes. cc @kristineds

**Comment by jaswsinc** [comment]
@raamdev I see we introduced conflicts in this branch. Sorry about that. I'm not certain what those are yet, but if there is any confusion just give me a shout.

**Comment by jaswsinc** [comment]
_Noting that this PR is still a work in progress; i.e., part of a larger picture._

**Comment by kristineds** [comment]
@raamdev All PRs (Step 1 - 5)  submitted for this [issue](https://github.com/websharks/zencache/issues/488)  are ready to be reviewed, merged, and tested by all of us. i.e. All work have been completed.

Pull Request Summary:
*Step 1*: websharks/zencache-pro#134
*Step 2*: websharks/zencache-pro#138
*Step 3*: websharks/zencache-pro#139
*Step 4*: websharks/zencache-pro#140
*Step 5*: websharks/zencache-pro#141

**Pull request merged**
