### PR TITLE
Improve Auto-Cache Engine error handling

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/zencache#643

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc This is ready for a review when you get a chance. :smile: Thanks!

**Comment by jaswsinc** [comment]
Reviewed. It all looks magical to me. No problems that I can find. Great!!!

**Comment by jaswsinc** [comment]
The only thing I noticed (very very minor), is that maybe you could change `strpos()` to `stripos()` whenever you test for `timeout` and `timed out`. That doesn't apply to the current release of WP though, so it's fine like it is. I had to hunt really hard to find something to complain about. haha

**Comment by raamdev** [comment]
@jaswsinc Sweet! Thank you for the review. :-) I changed `strpos()` to `stripos()`.

**Pull request closed without merging**
