### PR TITLE
Detect XML Sitemap URL for ACE; See: websharks/zencache#555

### PR DESCRIPTION
**Pull request by kristineds**
Detect when XML Sitemap URL exists for Auto Cache Engine; 
 - If not found, it displays this warning message

> The Auto-Cache Engine is currently configured with an XML Sitemap location that could not be found. We suggest that you install the [Google XML Sitemaps](http://zencache.com/r/google-xml-sitemaps-plugin/) plugin. Or, empty the XML Sitemap field and only use the list of URLs instead. See: **Dashboard → ZenCache → Auto-Cache Engine → XML Sitemap URL**

See: websharks/zencache#555

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting Pull request

**Comment by raamdev** [comment]
@kristineds Thanks! 

@jaswsinc I reviewed this and it looks ready to merge. I'll merge this once I get a 2nd review from you. :-)

**Comment by jaswsinc** [comment]
Looks good to me also :-)

**Comment by raamdev** [comment]
@kristineds Merged! Thank you! :100:

**Pull request merged**
