### PR TITLE
Add support for preview detection; See: websharks/zencache#583

### PR DESCRIPTION
**Pull request by kristineds**
Add support for preview detection; 

See: websharks/zencache#583

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting Pull Request

**Comment by raamdev** [comment]
@kristineds Reviewed. Looks great! The only thing I noticed is that the alignment of the comment block [here](https://github.com/websharks/zencache-pro/blob/feature/583/src/includes/closures/Ac/NcDebugConsts.php#L170-L175) is off. Can you fix that for me?

**Comment by jaswsinc** [comment]
Looks great :-)

**Comment by kristineds** [comment]
@raamdev Please review. :) https://github.com/websharks/zencache-pro/commit/6069f9122f0305f4f06d2f744d36ed624f06ee85

**Comment by raamdev** [comment]
@kristineds Merged! Thanks so much! :-)

@jaswsinc Thanks for the review!

**Pull request merged**
