### PR TITLE
Create ajaxWipeCdnCache() and ajaxClearCdnCache() methods; See: websharks/zencache#488

### PR DESCRIPTION
**Pull request by kristineds**
Create `ajaxWipeCdnCache()` and `ajaxClearCdnCache()` methods; 

See: websharks/zencache#488

### CODE REVIEW

**Comment by kristineds** [comment]
@raamdev  Please note that this work is incomplete at the moment. This is currently **Step 3** for the referenced GitHub issue: Clear CDN Cache button + option to clear CDN cache via "Clear Cache" toolbar button: https://github.com/websharks/zencache/issues/488

**Comment by jaswsinc** [comment]
https://github.com/websharks/zencache-pro/commit/f88606d4585bdeb96227e47212064135cf6ef0e5 includes some minor tweaks from me. These are to help clear a path for the next steps that I will document for Kristine shortly.

**Comment by kristineds** [comment]
@raamdev Completed additional work for Step 3 of this outline. Implementing CDN wipe/clear functionality: https://github.com/websharks/zencache-pro/commit/755ff64f6c3f19a2e42dc9105312ad3310a713da

**Comment by jaswsinc** [comment]
_Noting that this PR is still a work in progress; i.e., part of a larger picture._

**Comment by kristineds** [comment]
@raamdev All PRs (Step 1 - 5)  submitted for this [issue](https://github.com/websharks/zencache/issues/488)  are ready to be reviewed, merged, and tested by all of us. i.e. All work have been completed.

Pull Request Summary:
*Step 1*: websharks/zencache-pro#134
*Step 2*: websharks/zencache-pro#138
*Step 3*: websharks/zencache-pro#139
*Step 4*: websharks/zencache-pro#140
*Step 5*: websharks/zencache-pro#141

**Comment by raamdev** [comment]
Merged! Thank you.

**Pull request merged**
