### PR TITLE
Add expired transients menu option; See: websharks/zencache#459

### PR DESCRIPTION
**Pull request by kristineds**
Add expired transients menu option  in admin bar

ZenCache Pro Expired Transients Menu Option

See: websharks/zencache#459

### CODE REVIEW

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting ZenCache Pro Pull Request for adding the expired transients menu option https://github.com/websharks/zencache-pro/commit/a688387dd902c98ef9ad6330e8c078f64edd68f3

**Comment by jaswsinc** [comment]
## Next Actions

- Use same feature branch and push some additional tweaks.

- Install SASS utilities.

  ```bash
  $ brew install ruby;
  $ gem install sass;
  $ gem install sass-align;
  $ gem install bourbon;
  $ gem install scss_lint;
  ```
-  Start watching the SCSS file for the admin bar in ZenCache.

  ```bash
  $ cd ~/projects/websharks/zencache-pro/src/client-s/css
  $ sass --watch admin-bar.scss:admin-bar.min.css --style=compressed
  ```

- Replace [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/client-s/css/admin-bar/_wipe-clear.scss#L143) with the following:

  ```css
  min-width: 125px;
  ```

- After [this line](https://github.com/websharks/zencache-pro/blob/000000-dev/src/client-s/css/admin-bar/_wipe-clear.scss#L139) add the following:

  ```css
  .-transients-only {
    > a {
      @include sharkicon(feat-server);
    }
  }
  ```

- From the command line, stop watching the admin bar by typing `Ctrl-C` to exit.

- Test your changes to see how they look, and then submit a PR.

**Comment by jaswsinc** [comment]
@kristineds While working on the outline above, you can take note of the WebSharks font icon library demo [here](http://websharks.github.io/sharkicons/demo.html). Notice that `@include sharkicon(feat-server)` brings in the following icon for you automatically. Feel free to change that if you'd like.

**Comment by kristineds** [comment]
@jaswsinc I'm getting this error when trying to watch the SCSS file for the admin bar in ZenCache. Am I missing something? 

```
error admin-bar.scss (Line 3: File to import not found or unreadable: ../../vendor/package/bourbon/bourbon-v4.2.3/bourbon.)
[Listen warning]:
  Listen will be polling for changes. Learn more at https://github.com/guard/listen#polling-fallback.
```
@raamdev Thanks for the reminder! You are right, it slipped through. ;)

**Comment by jaswsinc** [comment]
> File to import not found or unreadable: ../../vendor/package/bourbon/bourbon-v4.2.3/bourbon.)

@kristineds So sorry. I left a step out. You can resolve this by running `composer install` from the `zencache-pro` repo directory.

```bash
$ cd ~/projects/websharks/zencache-pro
$ composer install
```

Then try again.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Icon added and width adjusted to `136px` to fit text for _Expired Transients_. https://github.com/websharks/zencache-pro/commit/b5774abaa182e0c9499e3c53d1dfa5bcec9a2512

ZC Expired Transients

**Comment by jaswsinc** [comment]
@kristineds I see `125px` wasn't enough. What you have looks great!

Two minor adjustments please:

- Please bump that from `136px` to `145px` to provide a little more breathing room in case of slight variations in font size from one browser to another, or from one fallback font to another.

- I see that you committed [a new file](https://github.com/websharks/zencache-pro/blob/b5774abaa182e0c9499e3c53d1dfa5bcec9a2512/admin-bar.min.css) by mistake. It looks like the problem you had with Sass left behind a log file. Please remove that on your next commit.

**Comment by kristineds** [comment]
@jaswsinc @raamdev Adjustments implemented. :+1: https://github.com/websharks/zencache-pro/commit/56d6bb6c2c3ca543129812db27e37b1e6c99a99b

- Bumped `136px` to `145px`

Expired Transients changed to 145px
- Deleted [this file](https://github.com/websharks/zencache-pro/commit/56d6bb6c2c3ca543129812db27e37b1e6c99a99b#diff-cfde5b2c6176a3f37eaf27a2b559d1fd) that was committed by mistake

**Comment by jaswsinc** [comment]
@kristineds Beautiful! I added one additional tweak to get that working in the alternative version of the admin bar where there is a split menu. See: https://github.com/websharks/zencache-pro/commit/e474e67d32f4228321feb3e7d67f140f6b661dc5




@raamdev This looks ready to merge to me. Tested, working.

**Comment by raamdev** [comment]
@jaswsinc I see that `clearExpiredTransients()` is used here (in the Clear Cache options menu on the Admin Bar), but I don't see where `wipeExpiredTransients()` is used. Is that just there for future use, or was something missed somewhere?

**Comment by jaswsinc** [comment]
> Is that just there for future use, or was something missed somewhere?

Yes, just there for future use; i.e., to keep all of the WCP routines uniform is all.

**Comment by raamdev** [comment]
> Yes, just there for future use;

Copy that. Thank you.

**Comment by raamdev** [comment]
@jaswsinc I noticed in this message when clearing Expired Transients, we say "expired rows from the database":



Wouldn't it be better to say "expired transients from the database"?

**Comment by raamdev** [comment]
Or even better, just "expired transients" (why do we need to say they were cleared from the "database"?). "Database" makes it sound more technical than it needs to be for novice site owners (scary even, "wait, I just cleared something from my database!?"). 

With other messages, like clearing cache files, we don't say "from the disk" but rather "cleared cache files for this site".

**Comment by jaswsinc** [comment]
> Or even better, just "expired transients"

Great point. Agree.

The number of _rows_ is a bit different from the number of _transients_ though, because each transient is associated with two rows in the DB. 1. The data. 2. The expiration time. So if we change the wording from rows to "transients" (which I agree with), then the total should generally be divided by two.

For me, I'd rather see the number of expired _rows_ that were removed myself, but I can also see where that is going to confuse most people. It's not really clear either way, because of the assumed two-row count for each transient. There's always the chance that some transients were corrupted in some way, and that expired rows were removed but without that coupling that would normally be expected.

**Comment by raamdev** [comment]
> For me, I'd rather see the number of expired rows that were removed myself,

Yeah, me too, but I'd rather err on the side of not confusing people, especially given that the message is just for informational purposes and not really debugging or anything.

**Comment by raamdev** [comment]
@jaswsinc Could you please review https://github.com/websharks/zencache-pro/commit/5b0e71f2b9ab5e165a4471243fe9af2d59644510 when you get a chance? If that looks good to you, I'll go ahead and merge this in. :-)

**Comment by jaswsinc** [comment]
Looks great!

**Comment by raamdev** [comment]
Merged! Awesome work @kristineds! :-)

**Comment by kristineds** [comment]
:+1:

**Pull request merged**
