### PR TITLE
Set a $network_wide default in case parameter is not passed to hook

### PR DESCRIPTION
**Pull request by raamdev**
See websharks/zencache#631

### CODE REVIEW

**Comment by raamdev** [comment]
@jaswsinc It looks like the issue was that the `$network_wide` parameter was not always being passed by the `plugin_activated` and `plugin_deactivated` hooks. I was able to reproduce the issue in my test environment consistently (occurred on every activate/deactivate of ZenCache Pro), and the change in this PR fixed the problem. Any objections here?

**Comment by raamdev** [comment]
@jaswsinc Also note that `$network_wide` defaults to false in WP Core: https://github.com/WordPress/WordPress/blob/60c8e272f50e5c34d9cf592d3440434aefd3fad5/wp-admin/includes/plugin.php#L518

**Comment by jaswsinc** [comment]
> I was able to reproduce the issue in my test environment consistently (occurred on every activate/deactivate of ZenCache Pro), and the change in this PR fixed the problem. Any objections here?

Nope, that looks good to me. Probably a good idea to make that an optional parameter anyway. However, I just noticed why we aren't getting the second argument there. We didn't ask for it. That's probably my mistake. See: https://github.com/websharks/zencache-pro/blob/6e5a0e642ea5e264ac2599807ba9558835cf1a9e/src/includes/classes/Plugin.php#L472-L473

**Comment by raamdev** [comment]
@jaswsinc Great catch! That would explain it! I was a little puzzled why that second parameter would not _always_ be passed after reviewing WP Core code. I've fixed this in https://github.com/websharks/zencache-pro/commit/1fdf6c8869cd456914dd4eb20dcc7d7f4431b515

**Pull request closed without merging**
